"""C code generator — emits a deployment harness from a .tgrs plan.

Backend selection implies the target platform:
- reference  → POSIX (load plan from file, malloc)
- esp-nn     → ESP-IDF (plan in flash partition, heap_caps, PSRAM)
- cmsis-nn   → Cortex-M bare metal (plan linked as extern symbol, static buffers)
"""

from __future__ import annotations

from tigris.emitters.binary.defs import FLAG_XIP
from tigris.emitters.binary.reader import read_binary_plan


BACKENDS = ("reference", "esp-nn", "cmsis-nn")


def generate_c(plan_data: bytes, backend: str) -> str:
    """Generate a C inference harness for the given plan and backend."""
    if backend not in BACKENDS:
        raise ValueError(f"Unknown backend: {backend!r}. Choose from: {', '.join(BACKENDS)}")

    plan = read_binary_plan(plan_data)
    xip = bool(plan["flags"] & FLAG_XIP)
    is_quantized = plan.get("num_quant_params", 0) > 0

    header_comment = _header_comment(plan, backend, xip)

    if backend == "esp-nn":
        return header_comment + _generate_esp(plan, is_quantized)
    elif backend == "cmsis-nn":
        return header_comment + _generate_cmsis(plan, is_quantized)
    else:
        return header_comment + _generate_posix(plan, is_quantized)


def _header_comment(plan: dict, backend: str, xip: bool) -> str:
    return f"""\
/*
 * Auto-generated by: tigris codegen --backend {backend}
 *
 * Model:   {plan['model_name']}
 * Ops:     {plan['num_ops']}
 * Stages:  {plan['num_stages']}
 * Weights: {plan['num_weights']}
 * Budget:  {plan['budget']} bytes
 * XIP:     {'yes' if xip else 'no'}
 */

"""


def _generate_posix(plan: dict, is_quantized: bool) -> str:
    dispatch = "tigris_dispatch_kernel_s8" if is_quantized else "tigris_dispatch_kernel"
    kernel_include = '#include "tigris_kernels_s8.h"' if is_quantized else '#include "tigris_kernels.h"'
    budget = plan["budget"] or 65536

    return f"""\
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "tigris.h"
#include "tigris_loader.h"
#include "tigris_mem.h"
#include "tigris_executor.h"
{kernel_include}

static uint8_t *load_file(const char *path, uint32_t *out_len)
{{
    FILE *f = fopen(path, "rb");
    if (!f) {{ perror(path); return NULL; }}
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t *buf = malloc((size_t)sz);
    if (buf) fread(buf, 1, (size_t)sz, f);
    fclose(f);
    *out_len = (uint32_t)sz;
    return buf;
}}

int main(int argc, char **argv)
{{
    if (argc < 2) {{
        fprintf(stderr, "Usage: %s <plan.tgrs>\\n", argv[0]);
        return 1;
    }}

    /* 1. Load plan from file */
    uint32_t plan_len = 0;
    uint8_t *plan_buf = load_file(argv[1], &plan_len);
    if (!plan_buf) return 1;

    tigris_plan_t plan;
    tigris_error_t err = tigris_plan_load(plan_buf, plan_len, &plan);
    if (err != TIGRIS_OK) {{
        fprintf(stderr, "Plan load failed: %s\\n", tigris_error_str(err));
        return 1;
    }}

    printf("Model:   %s\\n", tigris_model_name(&plan));
    printf("Ops:     %u  Stages: %u  Budget: %u bytes\\n",
           plan.header->num_ops, plan.header->num_stages, plan.header->budget);

    /* 2. Allocate buffers */
    uint32_t fast_size = plan.header->budget;
    if (fast_size == 0) fast_size = {budget};
    fast_size += tigris_weight_decompression_overhead(&plan);

    uint32_t slow_size = plan.header->peak * 4;
    if (slow_size < 256 * 1024) slow_size = 256 * 1024;

    void *fast_buf = malloc(fast_size);
    void *slow_buf = malloc(slow_size);
    uint16_t num_t = plan.header->num_tensors;
    void **tensor_ptrs = calloc(num_t, sizeof(void *));
    if (!fast_buf || !slow_buf || !tensor_ptrs) {{
        fprintf(stderr, "Allocation failed\\n");
        return 1;
    }}

    /* 3. Init memory manager */
    tigris_mem_t mem;
    tigris_mem_init(&mem, tensor_ptrs, num_t, fast_buf, fast_size, slow_buf, slow_size);

    /* 4. Allocate and zero-fill model inputs */
    for (uint8_t i = 0; i < plan.header->num_model_inputs; i++) {{
        uint16_t tidx = plan.model_inputs[i];
        tigris_mem_alloc_slow(&mem, tidx, plan.tensors[tidx].size_bytes);
        memset(mem.tensor_ptrs[tidx], 0, plan.tensors[tidx].size_bytes);
    }}

    /* 5. Run inference */
    tigris_exec_stats_t stats;
    tigris_exec_error_t eerr = tigris_run(&plan, &mem, {dispatch}, NULL, &stats);
    if (eerr != TIGRIS_EXEC_OK) {{
        fprintf(stderr, "Inference failed: %s\\n", tigris_exec_error_str(eerr));
        return 1;
    }}

    printf("OK  normal=%u tiled=%u chain=%u\\n",
           stats.stages_normal, stats.stages_tiled, stats.stages_chain);

    /* 6. Print outputs */
    for (uint8_t i = 0; i < plan.header->num_model_outputs; i++) {{
        uint16_t tidx = plan.model_outputs[i];
        const tigris_tensor_t *t = &plan.tensors[tidx];
        void *ptr = mem.tensor_ptrs[tidx];
        if (!ptr) continue;
        printf("Output '%s': %u bytes\\n", tigris_tensor_name(&plan, t), t->size_bytes);
        float *out = (float *)ptr;
        uint32_t n = t->size_bytes / sizeof(float);
        uint32_t show = n < 10 ? n : 10;
        for (uint32_t j = 0; j < show; j++)
            printf("  [%u] %.6f\\n", j, out[j]);
        if (n > show) printf("  ... (%u more)\\n", n - show);
    }}

    free(tensor_ptrs); free(slow_buf); free(fast_buf); free(plan_buf);
    return 0;
}}
"""


def _generate_esp(plan: dict, is_quantized: bool) -> str:
    budget = plan["budget"] or 65536

    if is_quantized:
        dispatch = "tigris_dispatch_kernel_esp_nn"
        kernel_includes = """\
#include "tigris_kernels_esp_nn.h"
#include "tigris_kernels_s8.h\""""
        prepare_block = """\

    /* ESP-NN scratch buffer setup */
    tigris_esp_nn_prepare(&plan, &mem);
"""
    else:
        dispatch = "tigris_dispatch_kernel"
        kernel_includes = '#include "tigris_kernels.h"'
        prepare_block = ""

    return f"""\
#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#include "esp_partition.h"
#include "esp_heap_caps.h"
#include "esp_timer.h"
#include "esp_log.h"

#include "tigris.h"
#include "tigris_loader.h"
#include "tigris_mem.h"
#include "tigris_executor.h"
{kernel_includes}

static const char *TAG = "tigris";

void app_main(void)
{{
    /* 1. Memory-map the plan partition */
    const esp_partition_t *part = esp_partition_find_first(
        ESP_PARTITION_TYPE_DATA, 0x40, "plan");
    if (!part) {{
        ESP_LOGE(TAG, "partition 'plan' not found");
        return;
    }}

    const void *mapped_ptr = NULL;
    esp_partition_mmap_handle_t mmap_handle;
    esp_err_t err = esp_partition_mmap(
        part, 0, part->size, ESP_PARTITION_MMAP_DATA, &mapped_ptr, &mmap_handle);
    if (err != ESP_OK) {{
        ESP_LOGE(TAG, "mmap failed: %s", esp_err_to_name(err));
        return;
    }}

    /* 2. Load the plan (zero-copy from flash) */
    const tigris_file_header_t *raw_hdr = (const tigris_file_header_t *)mapped_ptr;
    uint32_t plan_size = raw_hdr->file_size;

    tigris_plan_t plan;
    tigris_error_t perr = tigris_plan_load(
        (const uint8_t *)mapped_ptr, plan_size, &plan);
    if (perr != TIGRIS_OK) {{
        ESP_LOGE(TAG, "plan load failed: %s", tigris_error_str(perr));
        esp_partition_munmap(mmap_handle);
        return;
    }}

    printf("Model: %s  Ops: %u  Stages: %u\\n",
           tigris_model_name(&plan), plan.header->num_ops, plan.header->num_stages);

    /* 3. Allocate buffers */
    uint32_t fast_size = plan.header->budget;
    if (fast_size == 0) fast_size = {budget};
    fast_size += tigris_weight_decompression_overhead(&plan);

#if CONFIG_SPIRAM
    uint32_t slow_size = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
    if (slow_size > 64 * 1024) slow_size -= 16 * 1024;
#else
    uint32_t slow_size = heap_caps_get_largest_free_block(
        MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
    if (slow_size > 32 * 1024) slow_size -= 16 * 1024;
#endif
    if (slow_size < 64 * 1024) slow_size = 64 * 1024;

    void *fast_buf = heap_caps_malloc(fast_size,
        MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
#if CONFIG_SPIRAM
    void *slow_buf = heap_caps_malloc(slow_size, MALLOC_CAP_SPIRAM);
    uint16_t num_t = plan.header->num_tensors;
    void **tensor_ptrs = heap_caps_calloc(num_t, sizeof(void *), MALLOC_CAP_SPIRAM);
#else
    void *slow_buf = heap_caps_malloc(slow_size,
        MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
    uint16_t num_t = plan.header->num_tensors;
    void **tensor_ptrs = heap_caps_calloc(num_t, sizeof(void *),
        MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
#endif
    if (!fast_buf || !slow_buf || !tensor_ptrs) {{
        ESP_LOGE(TAG, "allocation failed");
        goto cleanup;
    }}

    printf("Fast: %lu  Slow: %lu\\n",
           (unsigned long)fast_size, (unsigned long)slow_size);

    /* 4. Init memory manager */
    tigris_mem_t mem;
    tigris_mem_init(&mem, tensor_ptrs, num_t, fast_buf, fast_size, slow_buf, slow_size);
{prepare_block}
    /* 5. Allocate and zero-fill model inputs */
    for (uint8_t i = 0; i < plan.header->num_model_inputs; i++) {{
        uint16_t tidx = plan.model_inputs[i];
        tigris_mem_alloc_slow(&mem, tidx, plan.tensors[tidx].size_bytes);
        memset(mem.tensor_ptrs[tidx], 0, plan.tensors[tidx].size_bytes);
    }}

    /* 6. Run inference */
    int64_t t0 = esp_timer_get_time();
    tigris_exec_stats_t stats;
    tigris_exec_error_t eerr = tigris_run(&plan, &mem, {dispatch}, NULL, &stats);
    int64_t t1 = esp_timer_get_time();

    if (eerr != TIGRIS_EXEC_OK) {{
        ESP_LOGE(TAG, "inference failed: %s", tigris_exec_error_str(eerr));
        goto cleanup;
    }}

    float elapsed_ms = (float)(t1 - t0) / 1000.0f;
    printf("Inference OK  %.1f ms  normal=%u tiled=%u chain=%u\\n",
           elapsed_ms, stats.stages_normal, stats.stages_tiled, stats.stages_chain);

    /* 7. Print outputs */
    for (uint8_t i = 0; i < plan.header->num_model_outputs; i++) {{
        uint16_t tidx = plan.model_outputs[i];
        const tigris_tensor_t *t = &plan.tensors[tidx];
        void *ptr = mem.tensor_ptrs[tidx];
        if (!ptr) continue;

        printf("Output '%s': %u bytes\\n", tigris_tensor_name(&plan, t), t->size_bytes);
        {"int8_t" if is_quantized else "float"} *out = ({"int8_t" if is_quantized else "float"} *)ptr;
        uint32_t n = t->size_bytes / {"1" if is_quantized else "sizeof(float)"};
        uint32_t show = n < 10 ? n : 10;
        for (uint32_t j = 0; j < show; j++)
            printf("  [%u] {"% d" if is_quantized else "%.6f"}\\n", j, {"(int)" if is_quantized else ""}out[j]);
        if (n > show) printf("  ... (%u more)\\n", n - show);
    }}

cleanup:
    heap_caps_free(tensor_ptrs);
    heap_caps_free(slow_buf);
    heap_caps_free(fast_buf);
    esp_partition_munmap(mmap_handle);
}}
"""


def _generate_cmsis(plan: dict, is_quantized: bool) -> str:
    dispatch = "tigris_dispatch_kernel_cmsis_nn" if is_quantized else "tigris_dispatch_kernel"
    kernel_include = '#include "tigris_kernels_cmsis_nn.h"' if is_quantized else '#include "tigris_kernels.h"'
    budget = plan["budget"] or 65536

    return f"""\
/*
 * Cortex-M deployment harness.
 *
 * The .tgrs plan must be linked into flash. Use your linker script or
 * objcopy to place it at a known address, then reference it here:
 *
 *   extern const uint8_t _binary_model_tgrs_start[];
 *   extern const uint8_t _binary_model_tgrs_end[];
 */

#include <stdio.h>
#include <string.h>

#include "tigris.h"
#include "tigris_loader.h"
#include "tigris_mem.h"
#include "tigris_executor.h"
{kernel_include}

/* Plan binary linked into flash — symbol provided by linker */
extern const uint8_t _binary_model_tgrs_start[];
extern const uint8_t _binary_model_tgrs_end[];

/* Static buffers — adjust sizes to match your target's SRAM */
static uint8_t fast_arena[{budget}] __attribute__((aligned(16)));
static uint8_t slow_arena[{max(budget * 4, 256 * 1024)}] __attribute__((aligned(16)));
static void *tensor_ptrs[{plan['num_tensors']}];

int main(void)
{{
    /* 1. Load plan from flash */
    uint32_t plan_len = (uint32_t)(_binary_model_tgrs_end - _binary_model_tgrs_start);

    tigris_plan_t plan;
    tigris_error_t err = tigris_plan_load(_binary_model_tgrs_start, plan_len, &plan);
    if (err != TIGRIS_OK) {{
        printf("Plan load failed: %s\\n", tigris_error_str(err));
        return 1;
    }}

    printf("Model: %s  Ops: %u  Stages: %u\\n",
           tigris_model_name(&plan), plan.header->num_ops, plan.header->num_stages);

    /* 2. Init memory manager */
    uint32_t fast_size = sizeof(fast_arena);
    fast_size += tigris_weight_decompression_overhead(&plan);
    /* Note: if decompression overhead > 0, increase fast_arena[] accordingly */

    tigris_mem_t mem;
    memset(tensor_ptrs, 0, sizeof(tensor_ptrs));
    tigris_mem_init(&mem, tensor_ptrs, {plan['num_tensors']},
                    fast_arena, sizeof(fast_arena),
                    slow_arena, sizeof(slow_arena));

    /* 3. Allocate and zero-fill model inputs */
    for (uint8_t i = 0; i < plan.header->num_model_inputs; i++) {{
        uint16_t tidx = plan.model_inputs[i];
        tigris_mem_alloc_slow(&mem, tidx, plan.tensors[tidx].size_bytes);
        memset(mem.tensor_ptrs[tidx], 0, plan.tensors[tidx].size_bytes);
    }}

    /* 4. Run inference */
    tigris_exec_stats_t stats;
    tigris_exec_error_t eerr = tigris_run(&plan, &mem, {dispatch}, NULL, &stats);
    if (eerr != TIGRIS_EXEC_OK) {{
        printf("Inference failed: %s\\n", tigris_exec_error_str(eerr));
        return 1;
    }}

    printf("OK  normal=%u tiled=%u chain=%u\\n",
           stats.stages_normal, stats.stages_tiled, stats.stages_chain);

    return 0;
}}
"""
